name: publish ghcr

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        id: docker_build
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.repository_owner }}/networktools:latest \
          -t ghcr.io/${{ github.repository_owner }}/networktools:latest-ci \
          -t ghcr.io/${{ github.repository_owner }}/networktools:${{ github.sha }} \
          -t networktools:latest \
          .

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: "networktools:latest"
      #     format: "table"
      #     exit-code: "0"
      #     ignore-unfixed: false
      #     vuln-type: "os,library"
      #     severity: "CRITICAL,HIGH"

      - name: Docker push
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/networktools --all-tags

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
